[unix_http_server]
file=/home/user/.var/run/supervisord.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=user
logfile=/home/user/logs/supervisord.log
pidfile=/home/user/.var/run/supervisord.pid
loglevel=info

[supervisorctl]
serverurl=unix:///home/user/.var/run/supervisord.sock

[include]
files = /etc/supervisor/conf.d/*.conf