# Generated by Django 5.2 on 2026-03-28 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oidc_sub', models.CharField(help_text='OIDC subject identifier from the identity provider', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='Email from OIDC provider', max_length=254, unique=True)),
                ('display_name', models.CharField(help_text='Display name from OIDC provider', max_length=255)),
                ('is_staff', models.BooleanField(default=False, help_text='Can access Django admin')),
                ('is_active', models.BooleanField(default=True, help_text='User is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['oidc_sub'], name='users_oidc_su_27b525_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx')],
            },
        ),
    ]
