# Generated by Django 5.2 on 2026-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Avatar/picture URL from OIDC provider', max_length=500, null=True),
        ),
    ]
