# Generated by Django 5.2 on 2026-03-28 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_add_data_dir_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list, help_text='List of messages in the conversation')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', help_text='Current status of the session', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace this session is bound to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='sessions_user_id_7acd24_idx'), models.Index(fields=['workspace'], name='sessions_workspa_a02b90_idx'), models.Index(fields=['status'], name='sessions_status_2c94db_idx')],
            },
        ),
    ]
