# Generated by Django 5.2 on 2026-03-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(blank=True, help_text='Reference to user who triggered the event', null=True)),
                ('oidc_sub', models.CharField(blank=True, help_text='OIDC subject identifier', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('WORKSPACE_CREATED', 'Workspace Created'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('WORKSPACE_STATUS_CHANGE', 'Workspace Status Change'), ('WORKSPACE_ERROR', 'Workspace Error'), ('PREVIEW_ACCESS', 'Preview Access'), ('PREVIEW_ACCESS_DENIED', 'Preview Access Denied'), ('FILE_MODIFIED', 'File Modified'), ('MESSAGE_SENT', 'Message Sent'), ('AGENT_RESPONSE', 'Agent Response'), ('DIND_CONNECTED', 'Dind Connected'), ('DIND_DISCONNECTED', 'Dind Disconnected'), ('DIND_HEALTH_CHECK_FAILED', 'Dind Health Check Failed'), ('DIND_ERROR', 'Dind Error')], max_length=50)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('operation', models.CharField(blank=True, help_text='create/modify/delete', max_length=20, null=True)),
                ('message_role', models.CharField(blank=True, help_text='user/agent', max_length=10, null=True)),
                ('message_summary', models.TextField(blank=True, help_text='Truncated message content', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for denial/error', max_length=100, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details (e.g., dind connection info)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['user_id'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['event_type'], name='audit_logs_event_t_3207df_idx'), models.Index(fields=['workspace_id'], name='audit_logs_workspa_2c03f6_idx')],
            },
        ),
    ]
