# Generated by Django 5.2 on 2026-03-28 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-defined name for the workspace', max_length=100)),
                ('container_id', models.CharField(blank=True, help_text='Docker container ID', max_length=64, null=True)),
                ('container_host', models.CharField(blank=True, help_text='Host:port for the container preview server', max_length=255, null=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error'), ('deleting', 'Deleting')], default='creating', help_text='Current status of the workspace', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if status is error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this workspace', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='workspaces_owner_i_04111b_idx'), models.Index(fields=['status'], name='workspaces_status_62c2f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_workspace_name_per_user')],
            },
        ),
    ]
