# Generated by Django 5.2 on 2026-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='data_dir_path',
            field=models.CharField(blank=True, help_text='Host path to user data directory (UUID-sharded structure)', max_length=512, null=True),
        ),
    ]
