# Generated by Django 5.2 on 2026-03-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_add_data_dir_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='URL-safe token string', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(help_text='Workspace this token authenticates', on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_tokens',
            },
        ),
    ]
